# Generated by Django 5.1.4 on 2024-12-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Motivational', 'Motivational'), ('Heartbreaking', 'Heartbreaking'), ('Exciting', 'Exciting'), ('Interesting', 'Interesting'), ('Horror', 'Horror')], max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
